### ISSUE TITLE
Serving JSPs this way breaks since Spring Boot v1.4.3.RELEASE

### ISSUE THREAD

**Issue by h143570** [ghillert/spring-boot-jsp-demo#2]
https://github.com/spring-projects/spring-boot/issues/8022

**Comment by ghillert** [comment]
Addressed with commit 98dd4d5be9bc8c85755cf0deb48d378cd7653735

Updates to Boot `1.5.1`. For the time being you have to declare an explicit version of `1.4.2.RELEASE` for the *Spring Boot Maven Plugin*. Version `1.4.3.RELEASE` does not work and seems to have introduced a breaking change.
